### ISSUE TITLE
minLevel option

### ISSUE THREAD

**Issue by fmenis** [tomer-yechiel/pino-sentry-transport#148]
**Bug description**
Hì! 
I think there is a bug in the `minLevel` option.
I configure `pino-sentry-transport` to send the logs with `minLevel: 40`.
So I expect that the `warn` and `error` logs are present on sentry.
After many attempts to sent a `log.warn` without result, I decrease the minLevel to 30 and then all the `warn' and `error` logs are correctly sent to sentry (but not the info logs).

**To Reproduce**
This is my configuration:
```
{
      target: 'pino-sentry-transport',
      options: {
        sentry: {
          dsn: process.env.SENTRY_DSN,
          environment: process.env.NODE_ENV,
        },
        withLogRecord: true,
        tags: ['id'],
        context: ['hostname'],
        minLevel: 40, // warn
      },
    }
```

**Expected behavior**
I expect that -  with  `minLevel: 40` - all `log.warn` are sent to sentry.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Node version [18.12.1]
 - Code Version [1.74.0]

**Comment by tomer-yechiel** [comment]
Thanks, the log sent to sentry if level > minLevel  i agree its confusing,

**Comment by fmenis** [comment]
@tomer-yechiel thanks for you quick reply,
Maybe could be useful to change the logic and log "if level >= minLevel"; or at least document the actual strange behavior in the documentation.

**Comment by tomer-yechiel** [comment]
fixed, thanks!
