### ISSUE TITLE
How should I init Sentry by myself with enabled skipSentryInitialization?

### ISSUE THREAD

**Issue by akhmadullin** [tomer-yechiel/pino-sentry-transport#219]
Hi!

**Problem**
I have my custom sentry init configuration and I init it in the root index file of my node.js app.

```js
// index.js

const { init, configureScope } = require('@sentry/node')

init({...})

configureScope(...)

const logger = require('./logger')
```

I use `pino` as logger, so I decided to save all `warn` and `error` logs to
* STDOUT
* Sentry (via `pino-sentry-transport`)

I use `skipSentryInitialization: true` in my config, because I init Sentry by myself in the root index file.

But with this configuration I have no logs in Sentry.

Without `skipSentryInitialization: true` logs appear in Sentry.

My logger configuration:

```js
// logger.js

const config = {
  level: 'info',
  transport: {
    targets: [
      {
        target: 'pino/file',
        options: {
          destination: 1, //  writes logs to STDOUT
        },
      },
      {
        target: 'pino-sentry-transport',
        options: {
          sentry: {
            dsn: '...',
          },
          withLogRecord: true,
          minLevel: pino.levels.values['warn'],
          skipSentryInitialization: true,
        },
      },
    ],
  },
}

module.exports = pino(config)
```

Errors thrown by hands (without pino) appear in Sentry.

Do you have any ideas why my Sentry init does not work with `skipSentryInitialization: true`? 
How can I init Sentry by myself with enabled `skipSentryInitialization`?

**Comment by tomer-yechiel** [comment]
Hello @akhmadullin 

Apologies for the delayed reply.

Thank you for bringing this issue to my attention. It appears that Sentry needs to be [explicitly initialized ](https://docs.sentry.io/platforms/javascript/configuration/webworkers/#usage-without-worker-level-initialization)for it to function within a Web Worker. As a result, the skipSentryInitialization is unnecessary.

please dont use it, it will be deprecated.

Once again, thank you.
