### ISSUE TITLE
Add support for Sentry breadcrumbs

### ISSUE THREAD

**Issue by amitav13** [tomer-yechiel/pino-sentry-transport#221]
**Is your feature request related to a problem? Please describe.**
I don't see other logs recorded through pino being added as breadcrumbs 

**Describe the solution you'd like**
Should be using Sentry's breadcrumb API to add in logs. I'm mostly interested in adding `info` logs, but could extend it to `warn` logs as well.

**Describe alternatives you've considered**
This is the only alternative I've seen so far - https://github.com/getsentry/sentry-javascript/issues/4192#issuecomment-1996847288

**Comment by tomer-yechiel** [comment]
Hi @amitav13, Sorry for the late response.
This is not in the scope of this package, this package enable sending errors/logs to Sentry.
Its not meant to be instrumentation package for Pino
