### ISSUE TITLE
Undefined error being sent to Sentry due to pino-abstract-transpot breaking change

### ISSUE THREAD

**Issue by dmuharemagic** [tomer-yechiel/pino-sentry-transport#222]
**Describe the bug**
It seems that the latest release to `pino-abstract-transport` has introduced a breaking change in a minor version (probably correlated to [v1.2.0](https://github.com/pinojs/pino-abstract-transport/releases/tag/v1.2.0)).

Serialized error is now not located in a nested `err` object, rather the root `obj` - https://github.com/tomer-yechiel/pino-sentry-transport/blob/main/src/index.ts#L97. 

This results into an `undefined` error being sent to Sentry.

**To Reproduce**
1. Install the dependency
2. Integrate with Sentry
3. Observe `undefined` being sent to Sentry, instead of the actual error

**Expected behavior**
The actual error contents should be extracted from the Pino logs and sent to Sentry.

**Screenshots**
<img width="419" alt="image" src="https://github.com/tomer-yechiel/pino-sentry-transport/assets/2150642/fe288565-f51f-4c49-b71e-66674162a20d">

This depicts the debug output of the `obj`, located [here](https://github.com/tomer-yechiel/pino-sentry-transport/blob/main/src/index.ts#L97).

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1
 - Node version: 20.12.2
 - Code version: [e.g. 1.1.0]

**Comment by tomer-yechiel** [comment]
Hi @dmuharemagic, I can't reproduce.
can you please provide how do you log the error with Pino?

**Comment by dmuharemagic** [comment]
Seems to be a misconfiguration on my side due to changing the expected structure of the error object. Sorry for the inconvenience.
