### ISSUE TITLE
Compatibility with sentry 8

### ISSUE THREAD

**Issue by wiese** [tomer-yechiel/pino-sentry-transport#223]
Sentry released [version 8](https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/) of its Javascript packages.

To allow users of the (great) pino-sentry-transport library to upgrade too it would be awesome to verify its compatibility with sentry 8 and indicate it in the peerDependencies.

**Comment by tomer-yechiel** [comment]
Hi @wiese
Thanks for letting me know

**Comment by tomer-yechiel** [comment]
update peer dependencies and include Pino V9 and Sentry V8

**Comment by wiese** [comment]
Thank you very much!
