### ISSUE TITLE
Unable to send any events/errors to Sentry

### ISSUE THREAD

**Issue by houserx-jmcc** [tomer-yechiel/pino-sentry-transport#224]
**Describe the bug**
First off, thanks for the transport! Hoping we can take advantage of it to make life easier in a Pino-centric way. 

Right now though, I am unable to send events/errors to Sentry via Pino logging.

**To Reproduce**
*logger.ts*
```ts
import { sentryBaseOptions } from '@/sentry';
import pino from 'pino';
import pinoHttp from 'pino-http';

// Overrideable for local, but defaults are production-ready
const pinoAutoLog = process.env.PINO_AUTOLOG === 'false' ? false : true
const pinoLevel = process.env.PINO_LEVEL || 'info'

const transports = [
  {
    target: 'pino/file',
    options: { destination: 1 }, // this works
  },
  {
    target: 'pino-sentry-transport',
    options: {
      sentry: { sentryBaseOptions }, // These options work - they're used in the main sentry init and return expected data currently
      withLogRecord: true, 
      tags: ['id'],
      context: ['hostname'],
      minLevel: 40, // warning
    },
  }
]

export const logger = pino({
  transport: { targets: transports },
  level: pinoLevel,
});

// pino-http uses pino as a parent logger and integrate with Express
export const expressLogger = pinoHttp({
  logger: logger,
  autoLogging: pinoAutoLog,
  useLevel: 'info'
});
```

**Expected behavior**
For test error 
`logger.error(new Error('bloop error'), "TEST ERROR, TODO REMOVE ME")`

In `stdout` we can see a test error, but it doesn't show up in Sentry:

```json
{
  "level": 50,
  "time": 1718827692926,
  "pid": 1,
  "hostname": "xxxxxx",
  "err": {
    "type": "Error",
    "message": "bloop error",
    "stack": "Error: bloop error\n  ... "
  },
  "msg": "TEST ERROR, TODO REMOVE ME"
}
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Alpine Linux
 - Node version 18.x
 - Code Version 1.2.0
 - Pino version 9.1.0
 - Sentry version 8.9.2

**Additional context**
The normal Sentry integrations are working as expected (console, auto-instrumented, etc.) but it is not picking up any Pino based errors for some reason.

I have also tried 
* `withLogRecord: false`, with no difference
* Using `pino-sentry-transport` as the only transport, with no difference
* Using a separate parent logger instance for `http-pino`, with no difference
* Adding the `level` for each transport when using multiple of them ([SO solution](https://stackoverflow.com/a/76625767)), with no difference

**Comment by houserx-jmcc** [comment]
After a lot of hair pulling, I started moving some of the code locally to attempt to debug further and immediately saw some red flags - [Hub is deprecated](https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#deprecate-hub) in Sentry v8:

![Screenshot 2024-06-19 at 8 02 35 PM](https://github.com/tomer-yechiel/pino-sentry-transport/assets/129085294/0a55f14e-96c0-404d-b723-16895cfca7d3)

**Comment by houserx-jmcc** [comment]
I also realized I didn't have `@sentry/types` installed, but that looks to be a dependency for this, not a devDependency. After installing that package, both transports were no longer working. Commenting out the sentry transport restored the stdout functionality. 

Maybe this will unlock some more debugging on my end, but I think `@sentry/types` likely should be upgraded as a dependency either way.

**Comment by tomer-yechiel** [comment]
Hi @houserx-jmcc 
I am unable to reproduce the issue using the versions you mentioned.
Can you please create a minimal reproducible example?

**Comment by houserx-jmcc** [comment]
Thanks for digging in with me! I also double checked and didn't see any discarded events in Sentry, so fairly sure we're not accidentally throwing them away from Inbound Filters in Sentry.

I did a few updates (that shouldn't matter) to our packages used and tested this via ts-node:

```json
"@sentry/node": "8.10.0",
"@sentry/profiling-node": "8.10.0",
"pino": "9.2.0",
"pino-sentry-transport": "1.2.0",
"ts-node": "10.9.2"
```

MVP:

```ts
//import { sentryBaseOptions } from '@/sentry';
import { NodeOptions } from '@sentry/node';
import pino from 'pino';

// setup
const dsn = ''
const environment = ''

const sentryBaseOptions: NodeOptions = {
  debug: false,
  environment: environment,
  dsn: dsn,
}

const transport = pino.transport({
  targets: [
    {
      target: 'pino/file',
      options: {
        destination: 1 // this writes to stdout
      },
      level: 'info'
    },
    {
      target: 'pino-sentry-transport',
      options: {
        sentry: { sentryBaseOptions },
      },
      level: 'error'
    }
  ]
})

export const logger = pino(transport);

// Log some stuff
logger.info("test")
logger.error(new Error('bloop error'), "This should show up in Sentry?")
logger.fatal(new Error('bloop error'), "This should show also up in Sentry?")
logger.info("test")
```

**Comment by houserx-jmcc** [comment]
Thanks for digging in with me! I also double checked and didn't see any discarded events in Sentry, so fairly sure we're not accidentally throwing them away from Inbound Filters in Sentry.

I did a few updates (that shouldn't matter) to our packages used and tested this via ts-node:

```json
"@sentry/node": "8.10.0",
"@sentry/profiling-node": "8.10.0",
"pino": "9.2.0",
"pino-sentry-transport": "1.2.0",
"ts-node": "10.9.2"
```

MVP:

```ts
//test.ts

import * as Sentry from '@sentry/node';
import pino from 'pino';

// setup
const dsn = ''
const environment = 'fusion'

const transport = pino.transport({
  targets: [
    {
      target: 'pino/file',
      options: {
        destination: 1 // this writes to stdout
      },
      level: 'debug'
    },
    {
      target: 'pino-sentry-transport',
      options: {
        sentry: {
          debug: false,
          environment: environment,
          dsn: dsn,
        },
      },
      level: 'debug'
    }
  ]
})

export const logger = pino(transport);

// Log some stuff
logger.info("test")
logger.fatal(new Error('bloop error'), "This should show up in Sentry?")
logger.info("test")

// Hit sentry directly (works)
Sentry.init({
  debug: false,
  environment: environment,
  dsn: dsn,
})
Sentry.captureException("This will definitely show up in Sentry!")
```

`npx ts-node test.ts`

Sentry:

<img width="1001" alt="Screenshot 2024-06-20 at 6 18 18 PM" src="https://github.com/tomer-yechiel/pino-sentry-transport/assets/129085294/751b8139-be79-4383-999c-2b181a67447a">

**Comment by houserx-jmcc** [comment]
Scratch my previous comments, there seemed to be a larger delay ingesting messages from pino vs directly, but the MVP turns out to actually work. Going to keep at it to whittle down things. My hunch is it has something to do with where/when the initial Sentry is [recommended](https://docs.sentry.io/platforms/javascript/guides/node/) to be init'd - this is changed a bit in v8 due to a greater focus on auto-instrumentation

**Comment by houserx-jmcc** [comment]
Okay, it seems like messages only get relayed from the transport *after* a direct Sentry message has been sent, for some reason. Maybe the init has a problem inside the transport?

```ts
import * as Sentry from '@sentry/node';
import pino from 'pino';

// setup
const dsn = ''
const environment = ''

const transport = pino.transport({
  targets: [
    {
      target: 'pino/file',
      options: {
        destination: 1 // this writes to stdout
      },
      level: 'debug'
    },
    {
      target: 'pino-sentry-transport',
      options: {
        sentry: {
          debug: false,
          environment: environment,
          dsn: dsn,
        },
        minLevel: 50
      },
      level: 'debug'
    }
  ]
})

export const logger = pino(transport);

// Log some stuff
logger.info("test")
logger.fatal(new Error('donatello kowabunga'), "turtle power")
logger.info("test")

Sentry.init({
  debug: false,
  environment: environment,
  dsn: dsn,
})

// Pause here - nothing sent to sentry
// uncomment and run again, now it works
//Sentry.captureMessage("After this, pino messages will show")
```

**Comment by tomer-yechiel** [comment]
@houserx-jmcc 
do you make the sure the process is not terminate before pino-sentry-transport send the message to Sentry?

**Comment by houserx-jmcc** [comment]
Not sure where the issue ended up being, but it works now 🤷🏻 Thanks the responses, and once again thanks for the transport!
