### ISSUE TITLE
Suggestion: Cleanup published package

### ISSUE THREAD

**Issue by TimShilov** [tomer-yechiel/pino-sentry-transport#226]
I have checked the published package contents and I think there are a lot of unnecessary files that IMO need to be added to `.npmignore`.
Those include:
1. Original source code.
2. `.github` directory.
3. Editor configuration directories (`.idea` and `.vscode`).
4. Unit tests
5. Build configuration and scripts 
6. Tool configurations (ava, ts, eslint)

![Screenshot 2024-07-02 at 13 34 33](https://github.com/tomer-yechiel/pino-sentry-transport/assets/20239045/dab4b1a1-8dea-4bf5-8737-ab719b10e6c1)

IMO all of those are not needed in the publisher package and they just bloat the package. There are literally more "useless" files than the actual code being used.
I'm happy to submit a PR if we agree on this.

**Comment by tomer-yechiel** [comment]
Hi @TimShilov 
sorry for late response, will do that in the next version
