### ISSUE TITLE
Support messageKey and errorKey

### ISSUE THREAD

**Issue by ceilfors** [tomer-yechiel/pino-sentry-transport#227]
**Is your feature request related to a problem? Please describe.**

Currently, we're getting `undefined` for all issues created through this transport.

<img width="215" alt="image" src="https://github.com/user-attachments/assets/614122d5-b92c-4948-ac44-bd8117c002cf">

This is because we're configuring pino like this

```
    return pino(
      {
        messageKey: 'message',
        errorKey: 'error',
```

**Describe the solution you'd like**

Make these two keys configurable, so the values are retrieved like this internally `obj[pinoSentryOptions.messageKey]`

**Comment by tomer-yechiel** [comment]
Thanks @ceilfors for opening this issue, I will work on that soon.

**Comment by tomer-yechiel** [comment]
add support for custom messageKey and errorKey in version 1.3.0 
should set expectPinoConfig to true

@ceilfors thanks again for opening this issue

**Comment by ceilfors** [comment]
Wow that's quick!
